class CfgITNCompat
{
//Accessories
	class accessories
	{
		class acc_flashlight;
		class deviceBase_m952;
		class deviceBase_la5b;
		class deviceBase_la5b_comboWO;
		class deviceBase_la5b_comboVIR;
		class deviceBase_ngal;
		class deviceBase_ngal_comboWO;
		class deviceBase_ngal_comboVIR;
				class GPLT_sideLAMG_1_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_gplt\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_gplt\ui\m300_bk"
					};
				};
				class GPLT_sidelima_LASER: deviceBase_la5b
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b",
						"Rsc_gjb_itn_la5b_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b"
					};
				};
				class GPLT_sidefoster_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{-0.140517,0.022622,-0.00231253},
						{-0.140517,0.022622,-0.00231253},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class Louetta_sidefsp_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class Louetta_sidefsp2_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class Louetta_sidefsp3_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sidehotch_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0.2,0.04,0.112},
						{0.2,0.04,0.112},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sidescar2_LASER: deviceBase_la5b_comboVIR
				{	
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sidescar_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sidetim_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sidetim3_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_SideMRAD_LASER: deviceBase_la5b
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b",
						"Rsc_gjb_itn_la5b_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b"
					};
				};
				class GPLT_sideurgi2_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sideurgi5_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sideurgi4_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sideurgi3_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sideurgi6_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sideurgi7_LASER: deviceBase_la5b_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b_combo",
						"Rsc_gjb_itn_la5b_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300_bk"
					};
				};
				class GPLT_sideurgi9_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sideurgi8_LASER: deviceBase_ngal_comboVIR
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"ngal_combo",
						"Rsc_gjb_itn_ngal_m300_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\ngal",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\m300"
					};
				};
				class GPLT_sidesass_p_LASER: deviceBase_la5b
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b",
						"Rsc_gjb_itn_la5b_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b"
					};
				};
				class GPLT_SideSASS_LASER: deviceBase_la5b
				{
					gjb_itn_memoryPoints[]=
					{
						{0,0,0},
						{0,0,0},
						{0,0,0}
					};
					gjb_itn_interface[]=
					{
						"la_5b",
						"Rsc_gjb_itn_la5b_gplt",
						"\gjb_itn\addons\gjb_itn_compat_t1\ui\la5b"
					};
				};
	};
class weapons
	{
		//HK416 D10
			class GPLT_tran_foster
			{
				gjb_itn_memoryPoints[]=
				{
					{-0.283867,0.046036,0.106207}
				};
			};
	};
};